### ISSUE TITLE
Fail to build project, Tesseract OCR is not installed properly

### ISSUE THREAD

**Issue by infojunkie** [jlpoolen/libreveris#8]
Running `ant` at the repo root, I get the following:

```
run:
     [java] Using /media/hdd/src/music/libreveris/config/logback.xml
     [java] INFO  Caller+0   at omr.WellKnowns.logDeclaredData(WellKnowns.java:454)
     [java]  - [Not running from jar]
     [java] INFO  Caller+0   at omr.Main.showEnvironment(Main.java:514)
     [java]  - Environment:
     [java] - Audiveris:    4.3.${program.revision}:${program.build}
     [java] - OS:           Linux 3.16.0-70-generic
     [java] - Architecture: amd64
     [java] - Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
     [java] INFO  Caller+0   at omr.Main.loadNativeLibraries(Main.java:439)
     [java]  - Loading native libraries ...
     [java] WARN  Caller+0   at omr.util.ClassUtil.loadLibrary(ClassUtil.java:181)
     [java]  - Error while loading library jniTessBridgejava.lang.UnsatisfiedLinkError: no jniTessBridge in java.library.path
     [java]     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
     [java]     at java.lang.Runtime.loadLibrary0(Runtime.java:870)
     [java]     at java.lang.System.loadLibrary(System.java:1122)
     [java]     at omr.util.ClassUtil.loadLibrary(ClassUtil.java:175)
     [java]     at omr.Main.loadNativeLibraries(Main.java:450)
     [java]     at omr.Main.doMain(Main.java:115)
     [java]     at Audiveris.main(Audiveris.java:47)
     [java] 
     [java] WARN  Caller+0   at omr.Main.loadNativeLibraries(Main.java:463)
     [java]  - Tesseract OCR is not installed properly

BUILD SUCCESSFUL
Total time: 6 seconds
```

How should I properly install Tesseract?

**Comment by jlpoolen** [comment]
I have no interest in the OCR of text, so I've ignored the Tesseract complaint.  What I would do is make (but not install) Tessseract manually, e.g. under /usr/local/src, and the modify the paths pointing to your headers/libraries in the just-installed Tesseract project under /usr/local/src.

**Comment by infojunkie** [comment]
Thanks. I'll try this and report back.
